version: '3.8'

services:
  backend:
    build: ./backend
    container_name: foodmart-backend
    ports:
      - "5003:5003"
    networks:
      - foodmart-net

  frontend:
    build: ./frontend 
    container_name: foodmart-frontend
    ports:
      - "5002:5002"
    networks:
      - foodmart-net
    depends_on:
      - backend

networks:
  foodmart-net: